name: RealStore
main: com.archmageinc.RealStore.RealStore
version: 0.1
description: Allow players to define a chest store front and set their prices based on in-game items.
commands:
  RealStore:
    aliases: rs
    description: Begin RealStore interaction. Options are <store>,<price>,<coffer>,<help>
    usage: Use '/rs help' for more information.
    permission: RealStore.*
    permission-message: You do not have permission to start RealStore interactions
permissions:
  RealStore.*:
    description: Allows a player to create coffers and stores
    default: true